version: '3.8'

services:
  pdf-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: poc-pdf-service
    ports:
      - "5005:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    shm_size: '1gb' # Crucial fix: expands memory available to the headless browser
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1536M
        reservations:
          memory: 512M